import { useEffect, useMemo, useState } from 'react';
import type { GiftConfig } from '../../content/gift';
import { inspecteur } from '../../content/inspecteur';
import casino from '../../assets/casino';
import desk from '../../assets/desk';
type Props={config:GiftConfig;soundOn:boolean;onSoundChange:(v:boolean)=>void;reducedMotion:boolean;onReducedMotionChange:(v:boolean)=>void};
type Place='wake'|'bar'|'office'|'case'|'final';
const placeLabel:Record<Place,string>={wake:'Suite de l’Inspecteur',bar:'Bar Teddy Bear',office:'Bureau des enquêtes',case:'Dossier 0808',final:'Salle des souvenirs'};
export function CaseExperience({config,soundOn,onSoundChange,reducedMotion,onReducedMotionChange}:Props){
 const [place,setPlace]=useState<Place>('wake'),[notebook,setNotebook]=useState(false),[magnify,setMagnify]=useState(false),[found,setFound]=useState<string[]>([]),[idle,setIdle]=useState('Il ajuste son chapeau et vérifie sa montre.');
 const [notice,setNotice]=useState(''); const complete=found.length===3;
 useEffect(()=>{const id=window.setTimeout(()=>setIdle('Il remarque votre présence, puis reprend son carnet.'),7000);return()=>window.clearTimeout(id)},[place]);
 useEffect(()=>{localStorage.setItem('casino-0808',JSON.stringify({place,found}))},[place,found]);
 const clue=(id:string,text:string)=>{setFound(v=>v.includes(id)?v:[...v,id]);setNotice(text)};
 const dossier=useMemo(()=>complete?'Tous les fragments sont classés. Le Casino se souvient.':'Il manque encore des fragments. L’Inspecteur ne tire jamais de conclusion trop vite.',[complete]);
 return <main className={reducedMotion?'casino-app still':'casino-app'}>
  <header className="field-header"><button className="badge" onClick={()=>setPlace('bar')} aria-label="Retourner au Bar Teddy Bear">IN</button><button className="location" onClick={()=>setNotebook(!notebook)}>{placeLabel[place]} <span>⌄</span></button><div><button onClick={()=>onSoundChange(!soundOn)}>{soundOn?'Son activé':'Son coupé'}</button><button onClick={()=>onReducedMotionChange(!reducedMotion)}>{reducedMotion?'Plans fixes':'Mouvement doux'}</button></div></header>
  {notebook&&<aside className="notebook"><button onClick={()=>setNotebook(false)}>Fermer le carnet ×</button><p className="case-stamp">Carnet de terrain</p><h2>{inspecteur.name}</h2><p>{inspecteur.title}</p><h3>Habitudes relevées</h3>{inspecteur.habits.map(x=><p key={x}>— {x}</p>)}<h3>Affaires classées</h3>{inspecteur.cases.map(x=><p key={x}>□ {x}</p>)}</aside>}
  {place==='wake'&&<section className="living-scene wake" style={{backgroundImage:`url(${desk})`}}><div className="scene-copy"><p className="case-stamp">07:08 — Le Casino dort encore</p><h1>Une patte. Une horloge.<br/><i>Deux essais.</i></h1><p>La première enquête de la journée : retrouver la loupe. Elle est, comme toujours, dans la poche du manteau.</p><button className="object-action" onClick={()=>{setNotice('Note : ne jamais croire l’Inspecteur quand il dit savoir où est sa loupe.');setPlace('bar')}}>Ajuster son chapeau <span>↘</span></button></div><div className="idle-caption">{idle}</div></section>}
  {place==='bar'&&<section className="living-scene bar" style={{backgroundImage:`url(${casino})`}}><div className="scene-copy"><p className="case-stamp">The King’s Casino — Bar Teddy Bear</p><h1>La table est<br/><i>réservée.</i></h1><p>Le Barman ne demande jamais la commande. Il connaît déjà la réponse.</p><div className="room-actions"><button onClick={()=>{setNotice('Une moustache de chocolat apparaît. Le Barman regarde. Le Doc regarde. Le Mafieux regarde. L’Inspecteur : « Quoi ? »')}}>Inspecter le chocolat chaud</button><button onClick={()=>{setNotice('Le Mafieux referme lentement « Statistiques sentimentales du King ». Personne ne pose de question.')}}>Écouter la table</button><button onClick={()=>setPlace('office')}>Suivre l’Inspecteur au bureau</button></div></div><div className="cast-caption">{inspecteur.cast.map(c=><p key={c.name}><b>{c.name}</b> — {c.role}</p>)}</div></section>}
  {place==='office'&&<section className="living-scene office" style={{backgroundImage:`url(${desk})`}}><div className="scene-copy"><p className="case-stamp">Bureau de l’Inspecteur — toujours ouvert</p><h1>Le Dossier<br/><i>0808.</i></h1><p>Quelqu’un tente d’effacer huit années de souvenirs. L’Inspecteur ne court pas après les réponses : il regarde d’abord ce que les autres ont cessé de voir.</p><button className="object-action" onClick={()=>setPlace('case')}>Ouvrir le dossier <span>↘</span></button></div></section>}
  {place==='case'&&<section className="investigation"><div className="investigation-copy"><p className="case-stamp">Dossier 0808 — L’Affaire du Meilleur Ami</p><h1>Regarder.<br/><i>Écouter. Relier.</i></h1><p>{dossier}</p><button className={magnify?'tool active':'tool'} onClick={()=>setMagnify(!magnify)}>⌕ {magnify?'Loupe active':'Prendre la loupe'}</button>{notice&&<p className="notice">{notice}</p>}{complete&&<button className="object-action" onClick={()=>setPlace('final')}>Classer l’affaire <span>↗</span></button>}</div><div className={magnify?'evidence-wall magnifying':'evidence-wall'}>{[['rain','La pluie remonte','Une tempête n’est pas toujours un danger.'],['clock','L’horloge arrêtée','Le temps a essayé. Le lien est resté.'],['thread','Le fil rouge','Huit années reliées par les bonnes personnes.']].map(([id,label,text],i)=><button key={id} className={`evidence e${i} ${found.includes(id)?'found':''}`} onClick={()=>magnify?clue(id,text):setNotice('L’Inspecteur tapote sa loupe : « Plus près, partenaire. »')}><span>{label}</span></button>)}</div></section>}
  {place==='final'&&<section className="living-scene finale" style={{backgroundImage:`url(${casino})`}}><div className="scene-copy"><p className="case-stamp">Affaire résolue — le Casino retrouve sa lumière</p><h1>Les grandes affaires<br/><i>ne parlent jamais de criminels.</i></h1><p>Elles parlent toujours des personnes qu’on refuse d’oublier.</p><p className="final-message">{config.birthdayMessage}</p><p className="signature">Ryad</p><button className="object-action" onClick={()=>setPlace('bar')}>Retourner au Bar Teddy Bear <span>↗</span></button></div><p className="ending-sign">THE KING’S CASINO<br/><span>Les portes restent ouvertes pour les vrais amis.</span></p></section>}
 </main>;
}
