import { useEffect, useState } from 'react';
import type { GiftConfig } from '../../content/gift';
import desk from '../../assets/desk';

type Props = { config: GiftConfig; soundOn: boolean; onSoundChange: (value: boolean) => void; reducedMotion: boolean; onReducedMotionChange: (value: boolean) => void };
const clues = [{ id:'photo', label:'Une photographie blanchie', text:'Un visage manque. Quelqu’un efface les traces.' }, { id:'watch', label:'Une montre arrêtée', text:'23 h 52. Il reste très peu de temps.' }, { id:'letter', label:'Une lettre sans encre', text:'Un seul mot résiste encore : Lawal.' }];
export function CaseExperience({ config, soundOn, onSoundChange, reducedMotion, onReducedMotionChange }: Props) {
  const [opened, setOpened] = useState(false); const [chapter, setChapter] = useState(0); const [clue, setClue] = useState<string | null>(null); const [known, setKnown] = useState<string[]>([]);
  useEffect(() => { const saved = localStorage.getItem('inspecteur-nounours-case'); if (saved) setOpened(true); }, []);
  const openCase = () => { setOpened(true); localStorage.setItem('inspecteur-nounours-case', 'opened'); };
  const inspect = (id: string) => { setClue(id); setKnown(current => current.includes(id) ? current : [...current, id]); };
  const next = () => setChapter(value => Math.min(value + 1, 3));
  if (!opened) return <section className="arrival" style={{backgroundImage:`url(${desk})`}}><div className="arrival-vignette"/><div className="arrival-copy"><p className="case-stamp">Bureau des affaires impossibles</p><p className="arrival-whisper">La pluie tombe. L’horloge attend.</p><h1>Tu arrives<br/><i>juste à temps.</i></h1><p className="arrival-brief">Quelqu’un efface les souvenirs de Lawal.</p><button className="case-button" onClick={openCase}>Ouvrir le dossier <span>↘</span></button></div><button className="quiet-control" onClick={() => onSoundChange(!soundOn)} aria-pressed={soundOn}>{soundOn ? 'Son : activé' : 'Vivre en silence'}</button></section>;
  return <main className={reducedMotion ? 'case-app motion-off' : 'case-app'}>
    <header className="case-header"><button className="seal" onClick={() => setChapter(0)} aria-label="Retour au prologue">IN</button><div><span>Affaire n° 08–LAWAL</span><strong>{config.caseTitle}</strong></div><div className="case-controls"><button onClick={() => onSoundChange(!soundOn)} aria-pressed={soundOn}>{soundOn ? 'Son' : 'Silence'}</button><button onClick={() => onReducedMotionChange(!reducedMotion)}>{reducedMotion ? 'Plans fixes' : 'Mouvement doux'}</button></div></header>
    {chapter === 0 && <section className="prologue" style={{backgroundImage:`url(${desk})`}}><div className="prologue-copy"><p className="case-stamp">Dossier confidentiel</p><h1>L’Inspecteur<br/>Nounours</h1><p>Les souvenirs ne disparaissent jamais sans laisser de trace.</p><button className="case-button" onClick={next}>Examiner les indices <span>↘</span></button></div><p className="subtitle">« Partenaire, la première règle : regarder deux fois. »</p></section>}
    {chapter === 1 && <section className="scene room-scene"><div className="scene-copy"><p className="case-stamp">Chapitre I — 01:12</p><h2>La chambre aux<br/><i>objets oubliés.</i></h2><p>Rien ne crie. Pourtant, quelque chose a cessé de se souvenir.</p><div className="clue-count">{known.length}/3 indices inspectés</div></div><div className="room" aria-label="Chambre à explorer">{clues.map((item,index) => <button key={item.id} className={`clue clue-${index} ${known.includes(item.id)?'found':''}`} onClick={() => inspect(item.id)}><span>{index+1}</span><b>{item.label}</b></button>)}</div>{clue && <aside className="evidence"><button onClick={() => setClue(null)} aria-label="Fermer">×</button><p className="case-stamp">Indice relevé</p><h3>{clues.find(item => item.id === clue)?.label}</h3><p>{clues.find(item => item.id === clue)?.text}</p>{known.length === 3 && <button className="case-button" onClick={next}>Prendre le train de minuit <span>↗</span></button>}</aside>}</section>}
    {chapter === 2 && <section className="scene train-scene"><div className="train-window"><span/><span/><span/></div><div className="scene-copy"><p className="case-stamp">Chapitre II — en route</p><h2>Le train<br/><i>de minuit.</i></h2><p>Les huit années ne se rangent pas dans l’ordre. Elles se retrouvent.</p><button className="case-button" onClick={next}>Entrer dans les archives <span>↘</span></button></div></section>}
    {chapter === 3 && <section className="scene attic-scene"><div className="scene-copy"><p className="case-stamp">Chapitre V — archives retrouvées</p><h2>Huit années.<br/><i>Un monde entier.</i></h2><p className="message">{config.birthdayMessage}</p><p className="signature">Une création de {config.creator}, pour {config.recipient}.</p></div><div className="timeline">{config.memories.map(memory => <article key={memory.year}><time>{memory.year}</time><h3>{memory.title}</h3><p>{memory.memory}</p></article>)}</div><footer>Affaire résolue <span>•</span> Certaines enquêtes durent toute une vie.</footer></section>}
  </main>;
}
