import { useEffect, useState } from 'react';
import type { GiftConfig } from '../../content/gift';
import casino from '../../assets/casino';
import desk from '../../assets/desk';
type Props={config:GiftConfig;soundOn:boolean;onSoundChange:(v:boolean)=>void;reducedMotion:boolean;onReducedMotionChange:(v:boolean)=>void};
type Room='hall'|'bar'|'office'|'archives'|'terrace'|'final';
const rooms:{id:Exclude<Room,'final'>;label:string;stamp:string;copy:string;asset:string;clue?:string}[]=[
 {id:'hall',label:'Le Hall',stamp:'Le King’s Casino',copy:'Les portraits vous regardent. Dans celui de l’Inspecteur, une oreille vient de bouger.',asset:casino},
 {id:'bar',label:'Bar Teddy Bear',stamp:'La table réservée',copy:'Le Barman pose un chocolat chaud. Une moustache apparaît sur le museau de l’Inspecteur. Personne ne dit rien. Long silence.',asset:casino,clue:'Le Barman a gardé la première lettre : « Certaines personnes reviennent toujours à la même table. »'},
 {id:'office',label:'Bureau',stamp:'Bureau de l’Inspecteur — toujours ouvert',copy:'La loupe est au milieu du bureau. Exactement là où il avait juré ne pas l’avoir laissée.',asset:desk,clue:'Sous le carnet : « Huit années ne se perdent pas. Elles attendent qu’on les regarde. »'},
 {id:'archives',label:'Archives',stamp:'Dossiers classés',copy:'La bibliothèque se déploie dans le noir. Un dossier tombe : « Projet commencé à 2 h 47 ». L’Inspecteur le remet à sa place, très sérieusement.',asset:desk,clue:'Dans le Dossier 0808 : « Le meilleur ami n’est pas un rôle. C’est une présence. »'},
 {id:'terrace',label:'Terrasse',stamp:'Les discussions infinies',copy:'La pluie ralentit. L’Inspecteur regarde le Casino, tapote sa montre, puis vous désigne une porte qui n’existait pas avant.',asset:casino},
];
export function CaseExperience({config,soundOn,onSoundChange,reducedMotion,onReducedMotionChange}:Props){
 const [started,setStarted]=useState(false),[room,setRoom]=useState<Room>('hall'),[lens,setLens]=useState(false),[clues,setClues]=useState<string[]>([]),[note,setNote]=useState('');const current=rooms.find(x=>x.id===room);
 useEffect(()=>{const raw=localStorage.getItem('casino-progress');if(raw){const p=JSON.parse(raw) as {clues:string[]};setClues(p.clues||[])}},[]);useEffect(()=>localStorage.setItem('casino-progress',JSON.stringify({clues})),[clues]);
 const discover=()=>{if(!current?.clue){setNote('L’Inspecteur souffle sur sa loupe. « Rien ici. Ce qui est rare, en soi. »');return}if(!lens){setNote('La loupe reste dans la poche. Approchez-la d’abord.');return}setClues(v=>v.includes(current.id)?v:[...v,current.id]);setNote(current.clue)};
 if(!started)return <section className="opening" style={{backgroundImage:`url(${desk})`}}><div className="rain"/><div className="opening-copy"><p className="case-stamp">The King’s Casino présente</p><h1>L’Inspecteur<br/><i>Nounours.</i></h1><p>Il existe des endroits où les gens ne viennent pas pour oublier la pluie. Ils viennent pour ne pas la traverser seuls.</p><button className="film-action" onClick={()=>setStarted(true)}>Entrer au Casino <span>↘</span></button></div><p className="opening-line">Une patte rate l’alarme. Une oreille se replie. L’enquête peut commencer.</p></section>;
 if(room==='final')return <section className="ending" style={{backgroundImage:`url(${casino})`}}><div className="ending-copy"><p className="case-stamp">Dossier 0808 — affaire résolue</p><h1>Les grandes affaires<br/><i>parlent des personnes.</i></h1><p className="birthday">{config.birthdayMessage}</p><p className="signature">Ryad, pour Lawal.</p><button className="film-action" onClick={()=>setRoom('bar')}>Retour au Bar Teddy Bear <span>↗</span></button></div><p className="casino-sign">THE KING’S CASINO<br/><span>Les portes restent ouvertes pour les vrais amis.</span></p></section>;
 return <main className={reducedMotion?'game still':'game'}><header className="game-header"><button className="mark" onClick={()=>setRoom('hall')}>IN</button><button className="lens" onClick={()=>setLens(!lens)} aria-pressed={lens}>⌕ {lens?'Loupe active':'Loupe'}</button><span>Dossier 0808 <b>{clues.length}/3</b></span><div><button onClick={()=>onSoundChange(!soundOn)}>{soundOn?'Son':'Silence'}</button><button onClick={()=>onReducedMotionChange(!reducedMotion)}>{reducedMotion?'Plans fixes':'Mouvement doux'}</button></div></header>
 <section className="world" style={{backgroundImage:`url(${current?.asset})`}}><div className="world-shade"/><div className="inspector" style={{backgroundImage:`url(${desk})`}} aria-label="L’Inspecteur Nounours observe la pièce"/><div className="world-copy"><p className="case-stamp">{current?.stamp}</p><h2>{current?.label}</h2><p>{current?.copy}</p><button className={lens?'inspect active':'inspect'} onClick={discover}>{lens?'Examiner le détail':'Sortir la loupe'} <span>⌕</span></button>{note&&<aside className="clue-note">{note}</aside>}</div><div className="doorway"><p>Portes du Casino</p>{rooms.filter(x=>x.id!=='hall').map(x=><button key={x.id} className={`door ${room===x.id?'here':''}`} onClick={()=>{setRoom(x.id);setNote('')}}><i/><span>{x.label}</span></button>)}{clues.length===3&&<button className="door gold" onClick={()=>setRoom('final')}><i/><span>Dossier 0808</span></button>}</div></section>
 </main>;
}
